before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
stages:
  - build
irrd image:
  stage: build
  tags: [network]
  rules:
    - if: $CI_COMMIT_BRANCH == "blade/master"
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
databases image:
  stage: build
  tags: [network]
  rules:
    - if: $CI_COMMIT_BRANCH == "blade/master"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - >
      docker build -f Dockerfile.databases --build-arg=$(date +%F)
      -t ${CI_REGISTRY_IMAGE}:data-$(date +%F)
      -t ${CI_REGISTRY_IMAGE}:data-latest
      .
    - docker push ${CI_REGISTRY_IMAGE}:data-$(date +%F)
    - docker push ${CI_REGISTRY_IMAGE}:data-latest
