before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
stages:
  - build
  - deploy
irrd image with database:
  stage: build
  tags: [network]
  rules:
    - if: $CI_COMMIT_BRANCH == "blade/master"
  script:
    - docker build --build-arg=TODAY=$(date +%F) -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest

rebuild cmdb:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  trigger:
    project: blade-group/infra/network/cmdb
    branch: master
